# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: namednativequeritest@localhost
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - uses: actions/checkout@v1

      - name: Verify mysql connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Execute DDL
        run: |
          sudo /etc/init.d/mysql start
          mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --database="$MYSQL_DATABASE" --execute="DROP DATABASE $MYSQL_DATABASE; CREATE DATABASE $MYSQL_DATABASE; CREATE TABLE IF NOT EXISTS 'user' ('id' bigint(20) NOT NULL AUTO_INCREMENT,'email' varchar(255) NOT NULL,'name' varchar(255) NOT NULL, PRIMARY KEY ('id'), UNIQUE KEY 'UK_ob8kqyqqgmefl0aco34akdtpe' ('email') ENGINE=InnoDB AUTO_INCREMENT=2130114 DEFAULT CHARSET=latin1;" 
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
