# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 5.7
          mysql database: namednativequeries  
          mysql root password: root
      - name: Verify mysql connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done
      - name: Run Script SQL
        run: |
          pwd
          ln -s /var/lib/mysql/mysql.sock /tmp/mysql.sock
          mysql -h 127.0.0.1 -P 3306 -u root -p namednativequeries
          mysql -u root -p namednativequeries < src/main/resources/bbdd.sql
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
